#!/bin/bash

echo "==============================="
echo "         ServerOS Info"
echo "==============================="
echo "Hostname : $(hostname)"
echo "Kernel   : $(uname -r)"
echo "Uptime   : $(uptime -p)"
echo "CPU      : $(lscpu | grep "Model name" | cut -d: -f2)"
echo "Memory   :"
free -h
echo
echo "Disk Usage:"
df -h /
